services:
  chartdb:
    image: ghcr.io/chartdb/chartdb:latest
    container_name: chartdb
    environment:
      DISABLE_ANALYTICS: true
    networks:
      - proxy

networks:
  proxy:
    external: true
