services:
  app:
    image: fedeabella/cloudflare-ddns
    container_name: cloudflare-ddns
    env_file: .env
    environment:
      - TZ=America/Montevideo
    read_only: true
    restart: always
    volumes:
      - ./domains.json:/app/domains.json
