services:
  protonmail-bridge:
    image: ghcr.io/videocurio/proton-mail-bridge:latest
    container_name: protonmail_bridge
    volumes:
      - mail_data:/root
    environment:
      CONTAINER_SMTP_PORT: 25
    networks:
      - mail
      - nextcloud-aio
    restart: always

networks:
  mail:
    external: true
  nextcloud-aio:
    external: true

volumes:
  mail_data:
