name: apache-guacamole

services:
  guacamole:
    image: docker.io/guacamole/guacamole
    container_name: guacamole
    env_file: .env
    environment:
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_HOSTNAME: guac-postgres
      POSTGRESQL_PASSWORD: "${POSTGRESQL_PASSWORD}"
      POSTGRESQL_USERNAME: "${POSTGRESQL_USERNAME}"
      POSTGRESQL_AUTO_CREATE_ACCOUNTS: true
      TOTP_ENABLED: TRUE
      REMOTE_IP_VALVE_ENABLED: true
      GUACD_HOSTNAME: guacd
      WEBAPP_CONTEXT: ROOT
    networks:
      - guacnetwork
      - proxy
    links:
      - guacd
    restart: always

  guacd:
    image: docker.io/guacamole/guacd
    container_name: guacd
    networks:
      - guacnetwork
    volumes:
      - ./FiraCodeNerdFontMono-Regular.ttf:/usr/share/fonts/truetype/firacode/FiraCodeNerdFontMono-Regular.ttf
    restart: always

  guac-postgres:
    image: docker.io/postgres:latest
    container_name: guac_db
    env_file: .env
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRESQL_DB: guacamole_db
      POSTGRESQL_PASSWORD: "${POSTGRESQL_PASSWORD}"
      POSTGRESQL_USERNAME: "${POSTGRESQL_USERNAME}"
    networks:
      - guacnetwork
    volumes:
      - ./db/db_data:/var/lib/postgresql/data:rw
      - ./init:/docker-entrypoint-initdb.d:ro
    restart: always

networks:
  guacnetwork:
    driver: bridge
  proxy:
    external: true
