services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    env_file: .env
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Montevideo
      DB_HOST: bookstack-mariadb
      DB_PORT: 3306
      DB_DATABASE: bookstack
      DB_USERNAME: "${MARIA_USERNAME}"
      DB_PASSWORD: "${MARIA_PASSWORD}"
    networks:
      - proxy
      - bookstack-internal
      - mail
    volumes:
      - /mnt/ext2/bookstack/config:/config
    restart: always

  bookstack-mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: bookstack-mariadb
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Montevideo
      MYSQL_ROOT_PASSWORD: "${MARIA_ROOTPASS}"
      MYSQL_DATABASE: bookstack
      MYSQL_USER: "${MARIA_USERNAME}"
      MYSQL_PASSWORD: "${MARIA_PASSWORD}"
    networks:
      bookstack-internal:
    volumes:
      - /mnt/ext2/bookstack/bookstack_db_data:/config

    restart: always

networks:
  bookstack-internal:
  proxy:
    external: true
  mail:
    external: true
