services:
  gotify:
    container_name: gotify
    image: gotify/server
    networks:
      - proxy
    volumes:
      - ./gotify_data:/app/data
    restart: always

networks:
  proxy:
    external: true
