services:
  gotify:
    container_name: gotify
    image: gotify/server
    environment:
      GOTIFY_DEFAULTUSER_PASS: "admin"
    networks:
      - gotify
    ports:
      - 8055:80
    volumes:
      - "./gotify_data:/app/data"
    restart: always

networks:
  gotify:
    name: notifications
