services:
  gotify:
    container_name: gotify
    image: gotify/server
    ports:
      - 8055:80
    environment:
      GOTIFY_DEFAULTUSER_PASS: "admin"
    volumes:
      - "./gotify_data:/app/data"
    restart: always
