services:
  cloudflare-ddns:
    image: fedeabella/cloudflare-ddns
    container_name: cloudflare-ddns
    env_file: .env
    environment:
      TZ: America/Montevideo
    read_only: true
    restart: always
    volumes:
      - type: bind
        source: ./config
        target: /app/config
