services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 111:1003
    ports:
      - 8096:8096
    volumes:
      - /opt/jellyfin:/config
      - /var/cache/jellyfin:/cache
      - /mnt/ext1/media:/media
    restart: always

  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    environment:
      - PUID=995
      - PGID=1003
      - TZ=America/Montevideo
      - UMASK=002
    networks:
      - media
    ports:
      - 9696:9696
    volumes:
      - /opt/prowlarr:/config
    restart: always

  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    environment:
      - PUID=994
      - PGID=1003
      - TZ=America/Montevideo
      - UMASK=002
    networks:
      - gotify
      - media
    ports:
      - 7878:7878
    volumes:
      - /opt/radarr:/config
      - /mnt/ext1:/data
    restart: always

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    environment:
      - PUID=114
      - GUID=1003
      - TZ=America/Montevideo
      - UMASK=002
    networks:
      - gotify
      - media
    ports:
      - 8989:8989
    volumes:
      - /opt/sonarr:/config
      - /mnt/ext1:/data
    restart: always

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=112
      - PGID=1003
      - TZ=America/Montevideo
      - UMASK=002
    networks:
      - media
    ports:
      - 8112:8112
      - 55666:55666
      - 55666:55666/udp
    volumes:
      - /opt/deluge:/config
      - /mnt/ext1:/data
    restart: always

networks:
  gotify:
    name: notifications
    external: true
  media:
    driver: bridge
