services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montevideo
      - UMASK=002
    volumes:
      - /var/lib/prowlarr:/config
    ports:
      - 9696:9696
    restart: always
    networks:
      - media

  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    environment:
      - PUID=994
      - PGID=1003
      - TZ=America/Montevideo
      - UMASK=007
    volumes:
      - /var/lib/radarr:/config
      - /mnt/ext1:/data
    ports:
      - 7878:7878
    restart: always
    networks:
      - gotify
      - media

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    environment:
      - PUID=114
      - PGID=1003
      - TZ=America/Montevideo
      - UMASK=007
    volumes:
      - /var/lib/sonarr:/config
      - /mnt/ext1:/data
    ports:
      - 8989:8989
    restart: always
    networks:
      - gotify
      - media

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=112
      - PGID=1003
      - TZ=America/Montevideo
    volumes:
      - /var/lib/deluge/.config/deluge:/config
      - /mnt/ext1:/data
    ports:
      - 8112:8112
      - 55666:55666
      - 55666:55666/udp
      - 58846:58846 #optional
    restart: always
    networks:
      - media

networks:
  gotify:
    name: notifications
    external: true
  media:
    driver: bridge
