services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    init: true
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=192.168.68.51
      - SKIP_DOMAIN_VALIDATION=false
      - NEXTCLOUD_DATADIR=/mnt/nextcloud
    ports:
      - 9999:8080
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      mail:
        ipv4_address: 172.0.5.10
      nextcloud-aio:
        ipv4_address: 172.25.5.0
    restart: always

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

networks:
  nextcloud-aio:
    name: nextcloud-aio
    ipam:
      config:
        - subnet: 172.25.0.0/16
          ip_range: 172.25.5.0/24
          gateway: 172.25.5.254
  mail:
    external: true
    name: mail
