services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    init: true
    environment:
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 192.168.68.51
      SKIP_DOMAIN_VALIDATION: false
      NEXTCLOUD_DATADIR: /mnt/nextcloud
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
      - nextcloud-aio
    restart: always

  whiteboard-server:
    image: ghcr.io/nextcloud-releases/whiteboard:release
    env_file:
      - .env
    networks:
      - nextcloud-aio

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

networks:
  nextcloud-aio:
    external: true
  proxy:
    external: true
