services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    env_file: .env
    environment:
      SECRET_ENCRYPTION_KEY: "${HOMARR_KEY}"
    networks:
      - proxy
      - nextcloud-aio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./appdata:/appdata
    restart: always

networks:
  proxy:
    external: true
  nextcloud-aio:
    external: true
