services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    env_file: .env
    environment:
      SECRET_ENCRYPTION_KEY: "${HOMARR_KEY}"
    networks:
      - internal
    ports:
      - 7575:7575
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./appdata:/appdata
    restart: always

networks:
  internal:
    name: internal
    external: true
