services:
  write:
    image: fedeabella/captain-write
    container_name: captain_write
    environment:
      - TZ=America/Montevideo
    restart: always
    volumes:
      - type: bind
        source: ./static
        target: /app/out
  serve:
    image: fedeabella/captain-serve
    container_name: captain_serve
    restart: always
    ports:
      - 8888:8000
    volumes:
      - type: bind
        source: ./static
        target: /app/static
        read_only: true
