services:
  captain-write:
    image: fedeabella/captain-write
    container_name: captain_write
    environment:
      TZ: America/Montevideo
    network_mode: none
    restart: always
    volumes:
      - type: bind
        source: ./static
        target: /app/out

  captain-serve:
    image: fedeabella/captain-serve
    container_name: captain_serve
    restart: always
    networks:
      - proxy
    volumes:
      - type: bind
        source: ./static
        target: /app/static
        read_only: true

networks:
  proxy:
    external: true
