services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    networks:
      - proxy
    volumes:
      - /opt/jellyfin:/config
      - /var/cache/jellyfin:/cache
      - /mnt/ext1/media:/media
    restart: always

networks:
  proxy:
    external: true
