services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    environment:
      TZ: America/Montevideo
      CRON_MIN: "2,32"
    logging:
      options:
        max-size: 10m
    networks:
      - proxy
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    restart: always

volumes:
  data:
  extensions:

networks:
  proxy:
    external: true
