services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: docker.io/jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 40080:80
      - 40443:443
      - 40081:81

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./98-themepark-npm:/etc/cont-init.d/99-themepark

    networks:
      - proxy

    environment:
      - TP_THEME=nord

networks:
  proxy:
    name: internal
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254
