services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: docker.io/jc21/nginx-proxy-manager:latest
    environment:
      TP_THEME: nord
    networks:
      - proxy
      - nextcloud-aio
    ports:
      - 40080:80
      - 40443:443
      - 40081:81
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./98-themepark-npm:/etc/cont-init.d/99-themepark
    restart: always

networks:
  proxy:
    external: true
  nextcloud-aio:
    external: true
